// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4930.DanceRobot;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainTalonSRXLeftBack1;
    public static SpeedController driveTrainTalonSRXLeftFront2;
    public static SpeedController driveTrainTalonSRXRightBack3;
    public static SpeedController driveTrainTalonSRXRightFront4;
    public static RobotDrive driveTrainRobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    	
    	//driveTrainTalonSRXLeftBack1 = new TalonSRX(0);
        driveTrainTalonSRXLeftBack1 = new CANTalon(0);
        LiveWindow.addActuator("DriveTrain", "TalonSRXLeftBack1", (TalonSRX) driveTrainTalonSRXLeftBack1);
        
        //driveTrainTalonSRXLeftFront2 = new TalonSRX(1);
        driveTrainTalonSRXLeftFront2 = new CANTalon(1);
        
        LiveWindow.addActuator("DriveTrain", "TalonSRXLeftFront2", (TalonSRX) driveTrainTalonSRXLeftFront2);
        
        //driveTrainTalonSRXRightBack3 = new TalonSRX(2);
        driveTrainTalonSRXRightBack3 = new CANTalon(2);
        LiveWindow.addActuator("DriveTrain", "TalonSRXRightBack3", (TalonSRX) driveTrainTalonSRXRightBack3);
        
        //driveTrainTalonSRXRightFront4 = new TalonSRX(3);
        driveTrainTalonSRXRightFront4 = new CANTalon(3);
        LiveWindow.addActuator("DriveTrain", "TalonSRXRightFront4", (TalonSRX) driveTrainTalonSRXRightFront4);
        
        driveTrainRobotDrive = new RobotDrive(driveTrainTalonSRXLeftBack1, driveTrainTalonSRXLeftFront2,
              driveTrainTalonSRXRightBack3, driveTrainTalonSRXRightFront4);
        
        driveTrainRobotDrive.setSafetyEnabled(true);
        driveTrainRobotDrive.setExpiration(0.1);
        driveTrainRobotDrive.setSensitivity(0.5);
        driveTrainRobotDrive.setMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
